apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels: {{ include "labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ default 3 .Values.revisionHistoryLimit }}
  strategy:
    type: {{ default "Recreate" .Values.strategy.type }}
  selector:
    matchLabels: {{ include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ template "image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.containerSecurityContext }}
        securityContext: {{- toYaml . | nindent 10 }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ template "configmap.fullname" . }}
        {{- with .Values.extraEnvFrom }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.extraEnvVars }}
        env: {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts: {{ include "volumeMounts" . | nindent 10 }}
        {{- if .Values.cache.enabled }}
          - name: cache
            mountPath: {{ .Values.cache.mountPath }}
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
          successThreshold: {{ .successThreshold }}
          failureThreshold: {{ .failureThreshold }}
        {{- end }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
          successThreshold: {{ .successThreshold }}
          failureThreshold: {{ .failureThreshold }}
        {{- end }}
        {{- end }}
        {{- if .Values.startupProbe.enabled }}
        {{- with .Values.startupProbe }}
        startupProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
          successThreshold: {{ .successThreshold }}
          failureThreshold: {{ .failureThreshold }}
        {{- end }}
        {{- end }}
      volumes: {{ include "volumes" . | nindent 8 }}
      {{- if .Values.cache.enabled }}
        - name: cache
          persistentVolumeClaim:
            claimName: {{ .Values.cache.existingClaim | default (printf "%s-cache" (include "fullname" .)) }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
