{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "pvc.fullname" . }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  accessModes:
  - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
{{- if and .Values.cache.enabled (not .Values.cache.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "fullname" . }}-cache
  annotations:
    helm.sh/resource-policy: keep
spec:
  {{- if .Values.cache.storageClass }}
  storageClassName: {{ .Values.cache.storageClass }}
  {{- end }}
  accessModes:
  - {{ .Values.cache.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.cache.size }}
{{- end }}
