apiVersion: v2
name: sonarr
description: Helm chart for Sonarr, a TV series collection manager for Usenet and BitTorrent users
type: application
version: 1.0.0
appVersion: "4.0.16"
home: https://sonarr.tv/
sources:
  - https://github.com/Sonarr/Sonarr
  - https://github.com/linuxserver/docker-sonarr
maintainers:
  - name: arturo
dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
