apiVersion: v2
name: tautulli
description: Helm chart for Tautulli, a monitoring and tracking tool for Plex Media Server
type: application
version: 1.0.0
appVersion: "v2.17.0"
home: https://tautulli.com/
sources:
  - https://github.com/Tautulli/Tautulli
  - https://github.com/Tautulli/Tautulli/pkgs/container/tautulli
maintainers:
  - name: arturo
dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
