apiVersion: v2
name: qbittorrent
description: Helm chart for qBittorrent, a BitTorrent client with a web UI
type: application
version: 1.0.1
appVersion: "5.1.4"
home: https://www.qbittorrent.org/
sources:
  - https://github.com/qbittorrent/qBittorrent
  - https://github.com/linuxserver/docker-qbittorrent
maintainers:
  - name: arturo
dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
