{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "pvc.fullname" . }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  accessModes:
  - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
{{- if and .Values.downloads.enabled (not .Values.downloads.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "pvc.fullname" . }}-downloads
  annotations:
    helm.sh/resource-policy: keep
spec:
  {{- if .Values.downloads.storageClass }}
  storageClassName: {{ .Values.downloads.storageClass }}
  {{- end }}
  accessModes:
  - {{ .Values.downloads.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.downloads.size }}
{{- end }}
