apiVersion: v2
name: cleanuparr
description: Helm chart for Cleanuparr, an automated cleanup tool for Sonarr and Radarr queues
type: application
version: 1.0.0
appVersion: "2.5.1"
home: https://github.com/Cleanuparr/Cleanuparr
sources:
  - https://github.com/Cleanuparr/Cleanuparr
  - https://github.com/Cleanuparr/Cleanuparr/pkgs/container/cleanuparr
maintainers:
  - name: arturo
dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
