apiVersion: v2
name: prowlarr
description: Helm chart for Prowlarr, an indexer manager and proxy for the arr stack
type: application
version: 1.0.0
appVersion: "2.3.5.5327"
home: https://prowlarr.com/
sources:
  - https://github.com/Prowlarr/Prowlarr
  - https://github.com/linuxserver/docker-prowlarr
maintainers:
  - name: arturo
dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
