apiVersion: v2
name: tdarr
description: Helm chart for Tdarr, a distributed video transcoding and health-checking system
type: application
version: 1.0.0
appVersion: "2.26.01"
home: https://tdarr.io/
sources:
  - https://github.com/HaveAGitGat/Tdarr
maintainers:
  - name: arturo
dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
