# Default values for tdarr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: "tdarr"

services:
  web:
    type: LoadBalancer
    annotations: {}
    externalTrafficPolicy: Cluster
    loadBalancerIP: ""
    clusterIP: ""
    ports:
    - name: web
      port: 8265
      targetPort: 8265
      protocol: TCP
  api:
    type: ClusterIP
    annotations: {}
    externalTrafficPolicy: Cluster
    loadBalancerIP: ""
    clusterIP: ""
    ports:
    - name: api
      port: 8266
      targetPort: 8266
      protocol: TCP

ingress:
  enabled: false
  annotations:
    cert-manager.io/cluster-issuer: cloudflare
  hosts:
  - tdarr.ar2ro.io
  tls:
  - hosts:
    - tdarr.ar2ro.io
    secretName: tdarr-tls

# Shared volumes accross all pods
volumes:
  media:
    mountPath: /media
    size: 10TiB
    accessMode: ReadWriteMany
    existingClaim: "pms-media"
    storageClassName: ""
    enabled: true
  transcode:
    mountPath: /transcode
    size: 10TiB
    accessMode: ReadWriteMany
    existingClaim: "pms-transcode"
    storageClassName: ""
    enabled: true


controller:
  image:
    repository: ghcr.io/haveagitgat/tdarr
    pullPolicy: Always
    tag: latest

  config:
    nodeName: TdarrController
    nodeID: TdarrContoller
    internalNode: "true"
    serverIP: 0.0.0.0
    serverPort: "8266"
    webUIPort: "8265"

  # Add NVIDIA_DRIVER_CAPABILITIES: all if nvidia gpu is passed through
  env:
    TZ: "American/Mexico_City"
    PUID: "1000"
    PGID: "1003"

  volumes:
    server:
      mountPath: /app/server
      size: 5Gi
      accessMode: ReadWriteOnce
      existingClaim: ""
      storageClassName: ""
      enabled: true
    config:
      mountPath: /app/configs
      size: 5Gi
      accessMode: ReadWriteOnce
      existingClaim: ""
      storageClassName: ""
      enabled: true

  resources:
    limits:
      cpu: "4"
      memory: "8192Mi"
    requests:
      cpu: "500m"
      memory: "512Mi"

  nodeSelector:
    netspeed: 10G

workers:
  image:
    repository: ghcr.io/haveagitgat/tdarr_node
    pullPolicy: Always
    tag: latest

  # For deployment whide volumes
  volumes:
    config:
      mountPath: /app/configs
      size: 5Gi
      accessMode: ReadWriteOnce
      existingClaim: ""
      storageClassName: ""
      enabled: true

  config:
    serverIP: tdarr-controller-api # if set it will override the autogenerated server endpoint
    serverPort: "8266"

  env:
    TZ: "America/Mexico_City"
    PUID: "1000"
    PGID: "1003"

  resources:
    limits:
      cpu: "4"
      memory: "4096Mi"
    requests:
      cpu: "500m"
      memory: "512Mi"

  nodes:
  # Example Node
  # All previous values in the worker section
  # will be passed down to the node and they can be overwriten.
  #
  # test-nvidia-node:
  #   resources:
  #     limit:
  #       nvidia.com/gpu: "1"
  #       cpu: 10
  #       memory: 10048Mi
  #   env:
  #     NVIDIA_DEVICE_CAPABILITIES: all
  #   nodeSelector:
  #     nvidia.com/gpu: "true"
    nvidia-2060:
      resources:
        limits:
          nvidia.com/gpu: "1"
          cpu: "4"
          memory: "8192Mi"
      env:
        NVIDIA_DEVICE_CAPABILITIES: all
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-GeForce-RTX-2060-SHARED
#    geonosis-cpu:
#      resources:
#        limits:
#          cpu: "7"
#          memory: "8192Mi"
