{{- range $k, $v := .Values.persistence -}}
{{- if $v.enabled }}
{{- if not $v.existingClaim }}
{{- if not $v.emptyDir }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "pvc.fullname" $ }}-{{ $k }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  {{- if $v.storageClass }}
  storageClassName: {{ $v.storageClass }}
  {{- end }}
  accessModes: 
  - {{ $v.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ $v.size }}
{{- end }}
{{- end }}
{{- end }}
{{- end -}}
