# Default values for unpackerr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/unpackerr/unpackerr
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

persistence:
  enabled: true
  mountPath: /config
  size: 1Gi
  storageClass: ""
  accessMode: ReadWriteOnce
  existingClaim: ""

extraVolumes: []
extraVolumeMounts: []
extraEnvVars: []

env:
  TZ: "America/New_York"
  UN_DEBUG: "false"
  UN_INTERVAL: "2m"
  UN_START_DELAY: "1m"
  UN_RETRY_DELAY: "5m"
  UN_MAX_RETRIES: "3"
  UN_PARALLEL: "1"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}
extraEnvFrom: []

podSecurityContext: {}

containerSecurityContext: {}

revisionHistoryLimit: 3

strategy:
  type: Recreate
