apiVersion: v2
name: scraparr
description: Helm chart for Scraparr, a tool for scraping and managing media metadata tags from Sonarr/Radarr
type: application
version: 1.0.0
appVersion: "latest"
home: https://github.com/thecfu/scraparr
sources:
  - https://github.com/thecfu/scraparr
maintainers:
  - name: arturo
dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
