apiVersion: v2
name: requestrr
description: Helm chart for Requestrr, a Discord chatbot for requesting media via Sonarr and Radarr
type: application
version: 1.0.0
appVersion: "v2.1.9"
home: https://github.com/thomst08/requestrr
sources:
  - https://github.com/thomst08/requestrr
  - https://hub.docker.com/r/thomst08/requestrr
maintainers:
  - name: arturo
dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
