apiVersion: apps/v1
kind: Deployment
metadata:
  {{- $name := printf "%s-controller" (include "fullname" .) }}
  name: {{ $name }}
  labels: {{ include "labels" $name | nindent 4}}
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "selectorLabels" $name | nindent 6 }}
  template:
    metadata:
      labels: {{ include "labels" $name | nindent 8 }}
    spec:
      containers:
      - name: contoller
        image: {{ include "controller-image" . }}
        envFrom:
        - configMapRef:
            name: {{ template "configmap.fullname" . }}-controller
        ports:
        {{- range $sname, $svc := .Values.services }}
        {{- range $port := $svc.ports }}
        - name: {{ $port.name }}
          protocol: {{ $port.protocol }}
          containerPort: {{ $port.targetPort }}
        {{- end }}
        {{- end }}
        - name: internal-node
          containerPort: 8267
          protocol: TCP
        - name: extra-node
          containerPort: 8267
          protocol: TCP
        volumeMounts:
        {{- range $name, $vol := .Values.volumes }}
        {{- if $vol.enabled }}
        - name: {{ $name }}
          mountPath: {{ $vol.mountPath }}
        {{- end }}
        {{- end }}
        {{- range $name, $vol := .Values.controller.volumes }}
        {{- if $vol.enabled }}
        - name: {{ $name }}
          mountPath: {{ $vol.mountPath }}
        {{- end }}
        {{- end }}
        resources: {{- toYaml .Values.controller.resources | nindent 10 }}
      volumes:
      {{- range $name, $vol := .Values.volumes }}
      {{- if $vol.enabled }}
      - name: {{ $name }}
        persistentVolumeClaim:
          claimName: {{ $vol.existingClaim | default (printf "%s-%s" (include "pvc.fullname" $) $name) }}
      {{- end }}
      {{- end }}
      {{- range $name, $vol := .Values.controller.volumes }}
      {{- if $vol.enabled }}
      - name: {{ $name }}
        persistentVolumeClaim:
          claimName: {{ $vol.existingClaim | default (printf "%s-controller-%s" (include "pvc.fullname" $) $name) }}
      {{- end }}
      {{- end }}
      {{- if .Values.controller.nodeSelector }}
      nodeSelector: {{- toYaml .Values.controller.nodeSelector | nindent 8 }}
      {{- end }}
