{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "pvc.fullname" . }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  accessModes:
  - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
{{- if and .Values.configs.enabled (not .Values.configs.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "pvc.fullname" . }}-configs
  annotations:
    helm.sh/resource-policy: keep
spec:
  {{- if .Values.configs.storageClass }}
  storageClassName: {{ .Values.configs.storageClass }}
  {{- end }}
  accessModes:
  - {{ .Values.configs.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.configs.size }}
{{- end }}
