{{- range $wname, $worker := .Values.workers.nodes }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- $name := printf "%s-node-%s" (include "fullname" $) $wname }}
  name: {{ $name }}
  labels: {{ include "labels" $name | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "selectorLabels" $name | nindent 6 }}
  template:
    metadata:
      labels: {{ include "labels" $name | nindent 8 }}
    spec:
      containers:
      - name: node
        image: {{ include "worker-image" $ }}
        envFrom:
        - configMapRef:
            name: {{ template "configmap.fullname" $ }}-{{ $wname }}
        ports:
        - name: internal-node
          protocol: TCP
          containerPort: 8267
        - name: extra-node
          protocol: TCP
          containerPort: 8268
        volumeMounts:
        {{- range $name, $vol := $.Values.volumes }}
        {{- if $vol.enabled }}
        - name: {{ $name }}
          mountPath: {{ $vol.mountPath }}
        {{- end  }}
        {{- end  }}
        {{- range $name, $vol := $.Values.workers.volumes }}
        {{- if $vol.enabled }}
        - name: {{ $name }}
          mountPath: {{ $vol.mountPath }}
        {{- end }}
        {{- end }}
        resources:
          {{- if $worker.resources }}
          {{- toYaml (merge $worker.resources $.Values.workers.resources) | nindent 10 }}
          {{- else }}
          {{- toYaml $.Values.workers.resources | nindent 10 }}
          {{- end }}
      volumes:
      {{- range $name, $vol := $.Values.volumes }}
      {{- if $vol.enabled }}
      - name: {{ $name }}
        persistentVolumeClaim:
          claimName: {{ $vol.existingClaim | default (printf "%s-%s" (include "pvc.fullname" $) $name) }}
      {{- end }}
      {{- end }}
      {{- range $name, $vol := $.Values.workers.volumes }}
      {{- if $vol.enabled }}
      - name: {{ $name }}
        persistentVolumeClaim:
          claimName: {{ $vol.existingClaim | default (printf "%s-node-%s-%s" (include "pvc.fullname" $) $wname $name) }}
      {{- end }}
      {{- end }}
      {{- if $worker.nodeSelector }}
      nodeSelector: {{- toYaml $worker.nodeSelector | nindent 8 }}
      {{- end }}
{{- end }}
