apiVersion: v2
name: checkrr
description: Helm chart for Checkrr, a service that checks media files for corruption and replaces them via Sonarr/Radarr
type: application
version: 1.0.0
appVersion: "latest"
home: https://github.com/aetaric/checkrr
sources:
  - https://github.com/aetaric/checkrr
maintainers:
  - name: arturo
dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
