apiVersion: v2
name: plexmediaserver
description: Helm chart for Plex Media Server, a media library and streaming application
type: application
version: 1.0.0
appVersion: "latest"
home: https://www.plex.tv/
sources:
  - https://github.com/linuxserver/docker-plex
  - https://hub.docker.com/r/linuxserver/plex
maintainers:
  - name: arturo
dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
