apiVersion: v2
name: nzbget
description: Helm chart for NZBGet, an efficient Usenet downloader
type: application
version: 1.0.0
appVersion: "latest"
home: https://nzbget.com/
sources:
  - https://github.com/nzbgetcom/nzbget
  - https://github.com/linuxserver/docker-nzbget
maintainers:
  - name: arturo
dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
