apiVersion: v2
name: jellyfin
description: Helm chart for Jellyfin, the free software media system
type: application
version: 1.0.0
appVersion: "10.11.6"
home: https://jellyfin.org/
sources:
  - https://github.com/jellyfin/jellyfin
  - https://hub.docker.com/r/jellyfin/jellyfin
maintainers:
  - name: arturo
dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
