{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "pvc.fullname" . }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  accessModes:
  - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
{{- if and .Values.transcode.enabled (not .Values.transcode.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "fullname" . }}-transcode
  annotations:
    helm.sh/resource-policy: keep
spec:
  {{- if .Values.transcode.storageClass }}
  storageClassName: {{ .Values.transcode.storageClass }}
  {{- end }}
  accessModes:
  - {{ .Values.transcode.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.transcode.size }}
{{- end }}
