apiVersion: v2
name: wizarr
description: Helm chart for Wizarr, an automatic user invitation and management system for Plex and Jellyfin
type: application
version: 1.0.1
appVersion: "v2026.4.0"
home: https://github.com/wizarrrr/wizarr
sources:
  - https://github.com/wizarrrr/wizarr
  - https://github.com/wizarrrr/wizarr/pkgs/container/wizarr
maintainers:
  - name: arturo
dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
